repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
        exclude: ^docs
    -   id: end-of-file-fixer
        exclude: ^docs
    -   id: trailing-whitespace
        exclude: ^docs
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff-format