repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
        exclude: ^docs
    -   id: end-of-file-fixer
        exclude: ^docs
    -   id: trailing-whitespace
        exclude: ^docs
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
