services:
  runner:
    build:
      context: .
      dockerfile: tox.Dockerfile
    tty: true
    volumes:
      - ./:/indico-client
      - ${INDICO_API_TOKEN_PATH:-$HOME/indico_api_token.txt}:/root/indico_api_token.txt
    environment:
      INDICO_HOST: ${INDICO_HOST:-dev-ci.us-east-2.indico-dev.indico.io}
